### ISSUE TITLE
Code of conduct (needed by 12/31/2015)

### ISSUE THREAD

**Issue by erikpmp** [RevolutionConf/website-2016#10]
* Copy verbiage from http://jsconf.com/codeofconduct.html
* Replace JSConf with RevolutionConf
* Style for consistence with RevolutionConf.com
* Make available at revolutionconf.com/codeofconduct (.something)

**Background**
Call for talks will open on Monday 1/5/2016 and we're going to link to the CoC.

**Comment by 1kevgriff** [comment]
Make sure there is a sub-note that we stole this from JSConf

**Comment by erikpmp** [comment]
disregard. just link to http://confcodeofconduct.com. Done.
